"""Build curated official-agenda sidecar CSVs for the 26 shared meetings.

Each entry: (item_number, parent, title, concept_id, votable_status).
Titles are transcribed from the official convocatoria/agenda document in the
document's original language (title_es column carries the original title).
Output: data/reference/official_agendas/<isin>_<meeting_date>.csv
"""
from __future__ import annotations

import csv
from pathlib import Path

OUT = Path("data/reference/official_agendas")
RETRIEVED = "2026-10-07"

B = "https://www.boe.es/diario_borme/txt.php?id="

# isin, date, source_url, source_ref, items
# items: (number, parent|None, title, concept, VOTABLE|INFORMATION_ONLY)
M: list[tuple[str, str, str, str, list[tuple[str, str | None, str, str, str]]]] = [

("ES0148396007", "2023-07-11", B + "BORME-C-2023-3863", "BORME-C-2023-3863", [
 ("1.a", "1", "Aprobación de las Cuentas Anuales e Informe de Gestión de Industria de Diseño Textil, S.A. correspondientes al ejercicio social 2022", "ACCOUNTS_SOLO", "VOTABLE"),
 ("1.b", "1", "Otorgamiento de la aprobación de la gestión social correspondiente al ejercicio social 2022", "DISCHARGE", "VOTABLE"),
 ("2", None, "Aprobación de las Cuentas Anuales e Informe de Gestión del grupo consolidado (Grupo Inditex) correspondientes al ejercicio social 2022", "ACCOUNTS_GROUP", "VOTABLE"),
 ("3", None, "Aprobación del Estado de Información no Financiera correspondiente al ejercicio social 2022", "EINF", "VOTABLE"),
 ("4", None, "Aplicación del resultado del ejercicio social 2022 y distribución de dividendos", "ALLOCATION", "VOTABLE"),
 ("5.a", "5", "Fijación del número de miembros del Consejo de Administración", "BOARD", "VOTABLE"),
 ("5.b", "5", "Reelección de Don Amancio Ortega Gaona, con la categoría de consejero dominical", "DIRECTOR_ELECTION", "VOTABLE"),
 ("5.c", "5", "Reelección de Don José Luis Durán Schulz, con la categoría de consejero independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6", None, "Aprobación de la Política de Remuneraciones de los Consejeros para los ejercicios 2024, 2025 y 2026", "REMUNERATION_POLICY", "VOTABLE"),
 ("7", None, "Aprobación de un plan de incentivo a largo plazo en efectivo y en acciones dirigido a miembros del equipo directivo, incluidos los consejeros ejecutivos, y otros empleados del Grupo Inditex", "LTIP", "VOTABLE"),
 ("8", None, "Autorización al Consejo de Administración para la adquisición derivativa de acciones propias, dejando sin efecto la autorización otorgada en la Junta General de Accionistas de 2019", "BUYBACK", "VOTABLE"),
 ("9", None, "Votación consultiva del Informe Anual de Remuneraciones de los Consejeros correspondiente al ejercicio social 2022", "REMUNERATION_REPORT", "VOTABLE"),
 ("10", None, "Otorgamiento de facultades para la ejecución de los acuerdos", "POWERS", "VOTABLE"),
 ("11", None, "Información a la Junta General de Accionistas sobre las modificaciones del Reglamento del Consejo de Administración", "BOARD_REGULATIONS", "INFORMATION_ONLY"),
]),

("ES0148396007", "2024-07-09", B + "BORME-C-2024-3451", "BORME-C-2024-3451", [
 ("1.a", "1", "Aprobación de las Cuentas Anuales e Informe de Gestión de Industria de Diseño Textil, Sociedad Anónima (Inditex, S.A.), correspondientes al ejercicio social 2023", "ACCOUNTS_SOLO", "VOTABLE"),
 ("1.b", "1", "Aprobación de la gestión social correspondiente al ejercicio social 2023", "DISCHARGE", "VOTABLE"),
 ("2", None, "Aprobación de las Cuentas Anuales e Informe de Gestión del grupo consolidado (Grupo Inditex) correspondientes al ejercicio social 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("3", None, "Aprobación del Estado de Información no Financiera correspondiente al ejercicio social 2023", "EINF", "VOTABLE"),
 ("4", None, "Aplicación del resultado del ejercicio social 2023 y distribución de dividendos", "ALLOCATION", "VOTABLE"),
 ("5.a", "5", "Modificación del artículo 9 (Transmisión de las acciones) del Título II de los Estatutos Sociales", "ARTICLES_AMEND", "VOTABLE"),
 ("5.b", "5", "Modificación de los artículos 15, 15 bis, 17, 18, 19 y 20 (Junta General de Accionistas) de los Estatutos Sociales", "ARTICLES_AMEND", "VOTABLE"),
 ("5.c", "5", "Modificación de los artículos 23 a 30 (Consejo de Administración) de los Estatutos Sociales", "ARTICLES_AMEND", "VOTABLE"),
 ("5.d", "5", "Modificación del artículo 36 (Aprobación de las cuentas y aplicación del resultado) de los Estatutos Sociales", "ARTICLES_AMEND", "VOTABLE"),
 ("5.e", "5", "Modificación del artículo 40 (Forma de liquidación) de los Estatutos Sociales", "ARTICLES_AMEND", "VOTABLE"),
 ("6", None, "Modificación del Reglamento de la Junta General de Accionistas", "ARTICLES_AMEND", "VOTABLE"),
 ("7.a", "7", "Nombramiento de Doña Flora Pérez Marcote, con la categoría de consejera dominical", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7.b", "7", "Nombramiento de Doña Belén Romana García, con la categoría de consejera independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7.c", "7", "Reelección de Doña Denise Patricia Kingsmill, con la categoría de consejera independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("8", None, "Votación consultiva del Informe Anual de Remuneraciones de los Consejeros correspondiente al ejercicio social 2023", "REMUNERATION_REPORT", "VOTABLE"),
 ("9", None, "Autorización para la reducción del plazo de la convocatoria de las Juntas Generales Extraordinarias", "MEETING_FORMALITY", "VOTABLE"),
 ("10", None, "Otorgamiento de facultades para la ejecución de los acuerdos", "POWERS", "VOTABLE"),
]),

("ES0144580Y14", "2024-05-17", B + "BORME-C-2024-957", "BORME-C-2024-957", [
 ("1", None, "Cuentas anuales 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("2", None, "Informes de gestión 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("3", None, "Estado de información no financiera 2023", "EINF", "VOTABLE"),
 ("4", None, "Gestión social y actuación del Consejo de Administración en 2023", "DISCHARGE", "VOTABLE"),
 ("5", None, "Reelección de KPMG Auditores, S.L. como auditor de cuentas", "AUDITOR", "VOTABLE"),
 ("6", None, "Modificación del Preámbulo y de los artículos 1, 4, 6, 7 y 8 de los Estatutos Sociales, así como adición de un Título Preliminar", "ARTICLES_AMEND", "VOTABLE"),
 ("7", None, "Modificación de los artículos 9, 12, 13, 14, 16, 18, 19, 22, 23, 27, 56 y 60 de los Estatutos Sociales", "ARTICLES_AMEND", "VOTABLE"),
 ("8", None, "Modificación de los artículos 10, 11, 12, 14, 16, 19, 20, 21, 22, 23, 27 y 40 del Reglamento de la Junta General de Accionistas", "ARTICLES_AMEND", "VOTABLE"),
 ("9", None, "Política de remuneraciones de los consejeros", "REMUNERATION_POLICY", "VOTABLE"),
 ("10", None, "Dividendo de involucración: aprobación y pago", "DIVIDEND", "VOTABLE"),
 ("11", None, "Aplicación del resultado y dividendo 2023: aprobación y pago complementario en el marco del sistema Iberdrola Retribución Flexible", "ALLOCATION", "VOTABLE"),
 ("12", None, "Primer aumento de capital liberado por un valor de mercado de referencia máximo de 2.600 millones de euros para implementar el sistema de dividendo opcional", "SHARE_ISSUANCE", "VOTABLE"),
 ("13", None, "Segundo aumento de capital liberado por un valor de mercado de referencia máximo de 1.700 millones de euros para implementar el sistema de dividendo opcional", "SHARE_ISSUANCE", "VOTABLE"),
 ("14", None, "Reducción de capital mediante la amortización de un máximo de 183.299.000 acciones propias (2,854% del capital social)", "CAPITAL_REDUCTION", "VOTABLE"),
 ("15", None, "Votación consultiva del Informe anual sobre remuneraciones de los consejeros y directivos 2023", "REMUNERATION_REPORT", "VOTABLE"),
 ("16", None, "Reelección de doña Nicola Mary Brewer como consejera independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("17", None, "Reelección de doña Regina Helena Jorge Nunes como consejera independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("18", None, "Reelección de don Íñigo Víctor de Oriol Ibarra como consejero externo", "DIRECTOR_ELECTION", "VOTABLE"),
 ("19", None, "Determinación del número de miembros del Consejo de Administración en catorce", "BOARD", "VOTABLE"),
 ("20", None, "Autorización para aumentar el capital social por un plazo máximo de cinco años con facultad de excluir el derecho de preferencia (límite conjunto del 10%)", "SHARE_ISSUANCE", "VOTABLE"),
 ("21", None, "Autorización para emitir obligaciones canjeables y/o convertibles en acciones y warrants por hasta 5.000 millones de euros y cinco años", "BONDS", "VOTABLE"),
 ("22", None, "Delegación de facultades para formalizar y elevar a público los acuerdos que se adopten", "POWERS", "VOTABLE"),
]),

("ES0144580Y14", "2025-05-30", B + "BORME-C-2025-994", "BORME-C-2025-994", [
 ("1", None, "Cuentas anuales 2024", "ACCOUNTS_GROUP", "VOTABLE"),
 ("2", None, "Informes de gestión 2024", "ACCOUNTS_GROUP", "VOTABLE"),
 ("3", None, "Estado de información no financiera 2024", "EINF", "VOTABLE"),
 ("4", None, "Gestión social y actuación del Consejo de Administración en 2024", "DISCHARGE", "VOTABLE"),
 ("5.1", "5", "Modificación de los Estatutos Sociales: organización corporativa y gobernanza — reforma de los artículos 7, 9 y 33", "ARTICLES_AMEND", "VOTABLE"),
 ("5.2", "5", "Modificación de los Estatutos Sociales: mejoras técnicas y de actualización — Preámbulo y artículos 5, 6, 20, 25, 27, 34 y 63", "ARTICLES_AMEND", "VOTABLE"),
 ("6.1", "6", "Modificación del Reglamento de la Junta General: incorporación de un Preámbulo", "ARTICLES_AMEND", "VOTABLE"),
 ("6.2", "6", "Modificación del Reglamento: involucración de los accionistas — Título I, artículos 1 a 6", "ARTICLES_AMEND", "VOTABLE"),
 ("6.3", "6", "Modificación del Reglamento: información facilitada a los accionistas — Título II, capítulos I-III", "ARTICLES_AMEND", "VOTABLE"),
 ("6.4", "6", "Modificación del Reglamento: clases, tipos de votaciones y competencias — Título III, artículos 19 a 21", "ARTICLES_AMEND", "VOTABLE"),
 ("6.5", "6", "Modificación del Reglamento: convocatoria, participación, asistencia y representación — Títulos IV y V", "ARTICLES_AMEND", "VOTABLE"),
 ("6.6", "6", "Modificación del Reglamento: organización, desarrollo y adopción de acuerdos — Títulos VI a X", "ARTICLES_AMEND", "VOTABLE"),
 ("6.7", "6", "Modificación del Reglamento: formas de celebración de la Junta — Título XI, artículos 49 a 61", "ARTICLES_AMEND", "VOTABLE"),
 ("6.8", "6", "Modificación del Reglamento: ámbito de aplicación y otras disposiciones — Título XII, artículos 62 a 65", "ARTICLES_AMEND", "VOTABLE"),
 ("7", None, "Dividendo de involucración: aprobación y pago", "DIVIDEND", "VOTABLE"),
 ("8", None, "Aplicación del resultado y dividendo 2024: aprobación y pago complementario en el marco del sistema Iberdrola Retribución Flexible", "ALLOCATION", "VOTABLE"),
 ("9", None, "Primer aumento de capital liberado por un valor de mercado de referencia máximo de 2.950 millones de euros para implementar el sistema de dividendo opcional", "SHARE_ISSUANCE", "VOTABLE"),
 ("10", None, "Segundo aumento de capital liberado por un valor de mercado de referencia máximo de 2.000 millones de euros para implementar el sistema de dividendo opcional", "SHARE_ISSUANCE", "VOTABLE"),
 ("11", None, "Reducción de capital mediante la amortización de un máximo de 200.561.000 acciones propias (3,114% del capital)", "CAPITAL_REDUCTION", "VOTABLE"),
 ("12", None, "Votación consultiva del Informe anual sobre remuneraciones de los consejeros y directivos 2024", "REMUNERATION_REPORT", "VOTABLE"),
 ("13", None, "Reelección de don Ángel Jesús Acebes Paniagua como consejero independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("14", None, "Reelección de don Juan Manuel González Serna como consejero independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("15", None, "Ratificación y reelección de doña Ana Colonques García-Planas como consejera independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("16", None, "Determinación del número de miembros del Consejo de Administración en catorce", "BOARD", "VOTABLE"),
 ("17", None, "Autorización para emitir obligaciones o bonos simples y otros valores de renta fija, no canjeables ni convertibles", "BONDS", "VOTABLE"),
 ("18", None, "Delegación de facultades para formalizar y elevar a público los acuerdos que se adopten", "POWERS", "VOTABLE"),
]),

("ES0113900J37", "2024-03-21", B + "BORME-C-2024-548", "BORME-C-2024-548", [
 ("1.a", "1", "Cuentas anuales e informes de gestión de Banco Santander, S.A. y de su grupo consolidado de 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("1.b", "1", "Estado de información no financiera consolidado de 2023 y que forma parte del informe de gestión consolidado", "EINF", "VOTABLE"),
 ("1.c", "1", "Gestión social durante 2023", "DISCHARGE", "VOTABLE"),
 ("2", None, "Aplicación de resultados de 2023", "ALLOCATION", "VOTABLE"),
 ("3.a", "3", "Fijación del número de consejeros", "BOARD", "VOTABLE"),
 ("3.b", "3", "Nombramiento de D. Juan Carlos Barrabés Cónsul", "DIRECTOR_ELECTION", "VOTABLE"),
 ("3.c", "3", "Nombramiento de Mr. Antonio Francesco Weiss", "DIRECTOR_ELECTION", "VOTABLE"),
 ("3.d", "3", "Reelección de D. Javier Botín-Sanz de Sautuola y O'Shea", "DIRECTOR_ELECTION", "VOTABLE"),
 ("3.e", "3", "Reelección de D. Germán de la Fuente Escamilla", "DIRECTOR_ELECTION", "VOTABLE"),
 ("3.f", "3", "Reelección de D. Henrique de Castro", "DIRECTOR_ELECTION", "VOTABLE"),
 ("3.g", "3", "Reelección de D. José Antonio Álvarez Álvarez", "DIRECTOR_ELECTION", "VOTABLE"),
 ("3.h", "3", "Reelección de Dña. Belén Romana García", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4", None, "Reelección del auditor de cuentas externo para el ejercicio 2024", "AUDITOR", "VOTABLE"),
 ("5.a", "5", "Autorización al consejo de administración para aumentar el capital social del Banco en una o varias veces", "SHARE_ISSUANCE", "VOTABLE"),
 ("5.b", "5", "Reducción del capital social por importe máximo de 783.428.928,50 euros, mediante amortización de acciones propias", "CAPITAL_REDUCTION", "VOTABLE"),
 ("5.c", "5", "Reducción del capital social por importe máximo de 791.278.928,50 euros, mediante amortización de acciones propias", "CAPITAL_REDUCTION", "VOTABLE"),
 ("6.a", "6", "Política de remuneraciones de los consejeros", "REMUNERATION_POLICY", "VOTABLE"),
 ("6.b", "6", "Fijación del importe máximo de la retribución anual a satisfacer al conjunto de los consejeros en su condición de tales", "REMUNERATION_POLICY", "VOTABLE"),
 ("6.c", "6", "Aprobación de la ratio máxima entre los componentes fijos y variables de la remuneración total de consejeros ejecutivos", "REMUNERATION_POLICY", "VOTABLE"),
 ("6.d", "6", "Plan de Retribución Variable Diferida y Vinculada a Objetivos Plurianuales", "LTIP", "VOTABLE"),
 ("6.e", "6", "Aplicación de la normativa de buy-outs del Grupo", "REMUNERATION_POLICY", "VOTABLE"),
 ("6.f", "6", "Informe anual sobre remuneraciones de los consejeros (votación consultiva)", "REMUNERATION_REPORT", "VOTABLE"),
 ("7", None, "Autorización al consejo y concesión de facultades para elevación a público", "POWERS", "VOTABLE"),
]),

("ES0113900J37", "2025-04-03", B + "BORME-C-2025-618", "BORME-C-2025-618", [
 ("1.a", "1", "Cuentas anuales e informes de gestión de Banco Santander, S.A., y de su grupo consolidado de 2024", "ACCOUNTS_GROUP", "VOTABLE"),
 ("1.b", "1", "Estado de información no financiera consolidado de 2024 y que forma parte del informe de gestión consolidado", "EINF", "VOTABLE"),
 ("1.c", "1", "Gestión social durante 2024", "DISCHARGE", "VOTABLE"),
 ("2", None, "Aplicación de resultados de 2024", "ALLOCATION", "VOTABLE"),
 ("3.a", "3", "Fijación del número de consejeros", "BOARD", "VOTABLE"),
 ("3.b", "3", "Reelección de D. Luis Isasi Fernández de Bobadilla", "DIRECTOR_ELECTION", "VOTABLE"),
 ("3.c", "3", "Reelección de D. Héctor Blas Grisi Checa", "DIRECTOR_ELECTION", "VOTABLE"),
 ("3.d", "3", "Reelección de Mr. Glenn Hogan Hutchins", "DIRECTOR_ELECTION", "VOTABLE"),
 ("3.e", "3", "Reelección de Mrs. Pamela Ann Walkden", "DIRECTOR_ELECTION", "VOTABLE"),
 ("3.f", "3", "Reelección de Dña. Ana Botín-Sanz de Sautuola y O'Shea", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4", None, "Reelección del auditor de cuentas externo para el ejercicio 2025", "AUDITOR", "VOTABLE"),
 ("5", None, "Nombramiento del verificador de la información sobre sostenibilidad para el ejercicio 2025", "AUDITOR", "VOTABLE"),
 ("6.a", "6", "Reducción del capital social por importe máximo de 706.871.648 euros, mediante amortización de acciones propias", "CAPITAL_REDUCTION", "VOTABLE"),
 ("6.b", "6", "Reducción del capital social por importe máximo de 757.624.616 euros, mediante amortización de acciones propias", "CAPITAL_REDUCTION", "VOTABLE"),
 ("7.a", "7", "Política de remuneraciones de los consejeros", "REMUNERATION_POLICY", "VOTABLE"),
 ("7.b", "7", "Fijación del importe máximo de la retribución anual a satisfacer al conjunto de los consejeros en su condición de tales", "REMUNERATION_POLICY", "VOTABLE"),
 ("7.c", "7", "Aprobación de la ratio máxima entre los componentes fijos y variables de la remuneración total de consejeros ejecutivos", "REMUNERATION_POLICY", "VOTABLE"),
 ("7.d", "7", "Plan de Retribución Variable Diferida y Vinculada a Objetivos Plurianuales", "LTIP", "VOTABLE"),
 ("7.e", "7", "Aplicación de la normativa de buyouts del Grupo", "REMUNERATION_POLICY", "VOTABLE"),
 ("7.f", "7", "Informe anual sobre remuneraciones de los consejeros (votación consultiva)", "REMUNERATION_REPORT", "VOTABLE"),
 ("8", None, "Autorización al consejo y concesión de facultades para elevación a público", "POWERS", "VOTABLE"),
]),

("ES0113211835", "2024-03-14",
 "https://accionistaseinversores.bbva.com/wp-content/uploads/2024/02/09022024HRPropuestasJGA2024_esp.pdf",
 "BBVA convocatoria JGA 2024 (issuer)", [
 ("1.1", "1", "Aprobación de las cuentas anuales y los informes de gestión de Banco Bilbao Vizcaya Argentaria, S.A. y de su Grupo consolidado correspondientes al ejercicio 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("1.2", "1", "Aprobación del estado de información no financiera de BBVA y de su Grupo consolidado correspondiente al ejercicio 2023", "EINF", "VOTABLE"),
 ("1.3", "1", "Aprobación de la aplicación del resultado del ejercicio 2023", "ALLOCATION", "VOTABLE"),
 ("1.4", "1", "Aprobación de la gestión social durante el ejercicio 2023", "DISCHARGE", "VOTABLE"),
 ("2.1", "2", "Reelección de D. José Miguel Andrés Torrecillas", "DIRECTOR_ELECTION", "VOTABLE"),
 ("2.2", "2", "Reelección de D. Jaime Félix Caruana Lacorte", "DIRECTOR_ELECTION", "VOTABLE"),
 ("2.3", "2", "Reelección de D.ª Belén Garijo López", "DIRECTOR_ELECTION", "VOTABLE"),
 ("2.4", "2", "Reelección de D.ª Ana Cristina Peralta Moreno", "DIRECTOR_ELECTION", "VOTABLE"),
 ("2.5", "2", "Reelección de D. Jan Paul Marie Francis Verplancke", "DIRECTOR_ELECTION", "VOTABLE"),
 ("2.6", "2", "Nombramiento de D. Enrique Casanueva Nárdiz", "DIRECTOR_ELECTION", "VOTABLE"),
 ("2.7", "2", "Nombramiento de D.ª Cristina de Parias Halcón", "DIRECTOR_ELECTION", "VOTABLE"),
 ("3", None, "Aprobación de la reducción del capital social del Banco hasta en un 10%, mediante amortización de acciones propias", "CAPITAL_REDUCTION", "VOTABLE"),
 ("4", None, "Aprobación de un nivel máximo de remuneración variable de hasta el 200% del componente fijo para un determinado colectivo de empleados", "REMUNERATION_POLICY", "VOTABLE"),
 ("5", None, "Delegación de facultades en el Consejo de Administración para formalizar, subsanar, interpretar y ejecutar los acuerdos", "POWERS", "VOTABLE"),
 ("6", None, "Votación consultiva del Informe Anual sobre Remuneraciones de los Consejeros de BBVA", "REMUNERATION_REPORT", "VOTABLE"),
]),

("ES0113211835", "2024-07-04", B + "BORME-C-2024-3268", "BORME-C-2024-3268", [
 ("1", None, "Aumento de capital social de BBVA por importe nominal máximo de 551.906.524,05 euros mediante emisión de hasta 1.126.339.845 acciones para atender la contraprestación de la oferta pública voluntaria de adquisición de acciones de Banco de Sabadell", "SHARE_ISSUANCE", "VOTABLE"),
 ("2", None, "Delegación de facultades en el Consejo de Administración para formalizar, subsanar, interpretar y ejecutar los acuerdos", "POWERS", "VOTABLE"),
]),

("ES0113211835", "2025-03-20",
 "https://accionistaseinversores.bbva.com/wp-content/uploads/2025/02/11022025HRConvocatoriaJGA_esp.pdf",
 "BBVA convocatoria JGA 2025 (issuer)", [
 ("1.1", "1", "Aprobación de las cuentas anuales y los informes de gestión de BBVA y de su Grupo consolidado correspondientes al ejercicio 2024", "ACCOUNTS_GROUP", "VOTABLE"),
 ("1.2", "1", "Aprobación del estado de información no financiera de BBVA y de su Grupo consolidado correspondiente al ejercicio 2024", "EINF", "VOTABLE"),
 ("1.3", "1", "Aprobación de la aplicación del resultado del ejercicio 2024", "ALLOCATION", "VOTABLE"),
 ("1.4", "1", "Aprobación de la gestión social durante el ejercicio 2024", "DISCHARGE", "VOTABLE"),
 ("2.1", "2", "Reelección de D. Carlos Torres Vila", "DIRECTOR_ELECTION", "VOTABLE"),
 ("2.2", "2", "Reelección de D. Onur Genç", "DIRECTOR_ELECTION", "VOTABLE"),
 ("2.3", "2", "Reelección de D.ª Connie Hedegaard Koksbang", "DIRECTOR_ELECTION", "VOTABLE"),
 ("3", None, "Aprobación de la reducción del capital social del Banco hasta en un 10%, mediante amortización de acciones propias", "CAPITAL_REDUCTION", "VOTABLE"),
 ("4", None, "Renovación de la delegación de facultades en el Consejo de Administración en relación con la ejecución del aumento y las reducciones de capital social", "SHARE_ISSUANCE", "VOTABLE"),
 ("5", None, "Aprobación de un nivel máximo de remuneración variable de hasta el 200% del componente fijo para un determinado colectivo de empleados", "REMUNERATION_POLICY", "VOTABLE"),
 ("6", None, "Reelección de los auditores de cuentas de BBVA y de su Grupo consolidado para 2025", "AUDITOR", "VOTABLE"),
 ("7", None, "Delegación de facultades en el Consejo de Administración para formalizar, subsanar, interpretar y ejecutar los acuerdos", "POWERS", "VOTABLE"),
 ("8", None, "Votación consultiva del Informe Anual sobre Remuneraciones de los Consejeros de BBVA", "REMUNERATION_REPORT", "VOTABLE"),
]),

("ES0140609019", "2024-03-21",
 "https://www.caixabank.com/deployedfiles/caixabank_com/Estaticos/PDFs/Accionistasinversores/Gobierno_Corporativo/JGA/2024/Convocatoria_2024_CAST.pdf",
 "CaixaBank convocatoria JGA 2024 (issuer)", [
 ("1.1", "1", "Aprobación de las cuentas anuales individuales y consolidadas, y de sus respectivos informes de gestión, del ejercicio 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("1.2", "1", "Aprobación del estado de información no financiera consolidado correspondiente al ejercicio 2023", "EINF", "VOTABLE"),
 ("1.3", "1", "Aprobación de la gestión del Consejo de Administración durante el ejercicio social 2023", "DISCHARGE", "VOTABLE"),
 ("2", None, "Aprobación de la propuesta de aplicación del resultado correspondiente al ejercicio 2023", "ALLOCATION", "VOTABLE"),
 ("3", None, "Reelección del auditor de cuentas de la Sociedad y de su grupo consolidado para el ejercicio 2024", "AUDITOR", "VOTABLE"),
 ("4", None, "Reelección de doña María Verónica Fisas Vergés", "DIRECTOR_ELECTION", "VOTABLE"),
 ("5.1", "5", "Reducción del capital social en 129.404.256 euros de nominal, mediante amortización de acciones propias", "CAPITAL_REDUCTION", "VOTABLE"),
 ("5.2", "5", "Reducción de capital por un importe máximo equivalente al 10% del capital social", "CAPITAL_REDUCTION", "VOTABLE"),
 ("5.3", "5", "Autorización al Consejo de Administración para la adquisición derivativa de acciones propias", "BUYBACK", "VOTABLE"),
 ("5.4", "5", "Delegación en el Consejo de Administración de la facultad de emitir valores convertibles", "BONDS", "VOTABLE"),
 ("6.1", "6", "Aprobación de la modificación de la política de remuneraciones de los consejeros", "REMUNERATION_POLICY", "VOTABLE"),
 ("6.2", "6", "Entrega de acciones a favor de los consejeros ejecutivos de la Sociedad como pago de retribución variable", "REMUNERATION_POLICY", "VOTABLE"),
 ("6.3", "6", "Aprobación del nivel máximo de retribución variable para los empleados con impacto significativo en el perfil de riesgo", "REMUNERATION_POLICY", "VOTABLE"),
 ("6.4", "6", "Votación consultiva del Informe Anual sobre Remuneraciones de los miembros del Consejo de Administración 2023", "REMUNERATION_REPORT", "VOTABLE"),
 ("7", None, "Autorización y delegación de facultades para la interpretación, subsanación, ejecución y formalización de los acuerdos", "POWERS", "VOTABLE"),
 ("8.1", "8", "Información sobre la modificación del Reglamento del Consejo de Administración", "BOARD_REGULATIONS", "INFORMATION_ONLY"),
 ("8.2", "8", "Comunicación del informe del Consejo de Administración a los efectos de lo dispuesto en el artículo 511 de la Ley de Sociedades de Capital", "BONDS", "INFORMATION_ONLY"),
]),

("ES0140609019", "2025-04-10",
 "https://www.caixabank.com/deployedfiles/caixabank_com/Estaticos/PDFs/Accionistasinversores/Gobierno_Corporativo/JGA/2025/Convocatoria_2025_CAST.pdf",
 "CaixaBank convocatoria JGA 2025 (issuer)", [
 ("1.1", "1", "Aprobación de las cuentas anuales individuales y consolidadas, y de sus respectivos informes de gestión, del ejercicio 2024", "ACCOUNTS_GROUP", "VOTABLE"),
 ("1.2", "1", "Aprobación del estado de información no financiera consolidado correspondiente al ejercicio 2024", "EINF", "VOTABLE"),
 ("1.3", "1", "Aprobación de la gestión del Consejo de Administración durante el ejercicio social 2024", "DISCHARGE", "VOTABLE"),
 ("2", None, "Aprobación de la propuesta de aplicación del resultado correspondiente al ejercicio 2024", "ALLOCATION", "VOTABLE"),
 ("3", None, "Reelección del auditor de cuentas de la Sociedad y de su grupo consolidado para el ejercicio 2025", "AUDITOR", "VOTABLE"),
 ("4.1", "4", "Reelección de doña Koro Usarraga Unsain", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.2", "4", "Reelección de don Fernando Maria Costa Duarte Ulrich", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.3", "4", "Reelección de doña Teresa Santero Quintillá", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.4", "4", "Nombramiento de doña Rosa María García Piñeiro", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.5", "4", "Nombramiento de don Luis Álvarez Satorre", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.6", "4", "Nombramiento de don Bernardo Sánchez Incera", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.7", "4", "Nombramiento de don Pablo Arturo Forero Calderón", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.8", "4", "Nombramiento de don José María Méndez Álvarez-Cedrón", "DIRECTOR_ELECTION", "VOTABLE"),
 ("5.1", "5", "Autorización para que la Sociedad pueda adquirir acciones propias (adquisición derivativa)", "BUYBACK", "VOTABLE"),
 ("5.2", "5", "Reducción de capital por un importe máximo equivalente al 10% del capital social", "CAPITAL_REDUCTION", "VOTABLE"),
 ("6.1", "6", "Fijación de la remuneración de los consejeros", "REMUNERATION_POLICY", "VOTABLE"),
 ("6.2", "6", "Aprobación de la Política de Remuneración del Consejo de Administración", "REMUNERATION_POLICY", "VOTABLE"),
 ("6.3", "6", "Entrega de acciones a favor de los consejeros ejecutivos como pago de retribución variable", "REMUNERATION_POLICY", "VOTABLE"),
 ("6.4", "6", "Aprobación del nivel máximo de retribución variable para los empleados con impacto significativo en el perfil de riesgo", "REMUNERATION_POLICY", "VOTABLE"),
 ("6.5", "6", "Votación consultiva del Informe Anual sobre Remuneraciones de los miembros del Consejo de Administración 2024", "REMUNERATION_REPORT", "VOTABLE"),
 ("7", None, "Autorización y delegación de facultades para la interpretación, subsanación, ejecución y formalización de los acuerdos", "POWERS", "VOTABLE"),
 ("8.1", "8", "Información sobre la modificación del Reglamento del Consejo de Administración", "BOARD_REGULATIONS", "INFORMATION_ONLY"),
 ("8.2", "8", "Comunicación del informe del Consejo de Administración a los efectos de lo dispuesto en el artículo 511 de la Ley de Sociedades de Capital", "BONDS", "INFORMATION_ONLY"),
]),

("ES0105066007", "2024-04-25",
 "https://www.cellnex.com/app/uploads/2024/03/01.-Anuncio-de-convocatoria.pdf",
 "Cellnex anuncio convocatoria JGA 2024 (issuer)", [
 ("1", None, "Aprobación de las cuentas anuales individuales e informe de gestión y de las cuentas anuales consolidadas e informe de gestión (información financiera) del ejercicio 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("2", None, "Aprobación de la información no financiera contenida en el informe de gestión consolidado del ejercicio 2023", "EINF", "VOTABLE"),
 ("3", None, "Aprobación de la propuesta de aplicación del resultado del ejercicio 2023", "ALLOCATION", "VOTABLE"),
 ("4", None, "Aprobación de la gestión del Consejo de Administración durante el ejercicio 2023", "DISCHARGE", "VOTABLE"),
 ("5", None, "Nombramiento de Auditores de Cuentas para la Sociedad y su grupo consolidado para los ejercicios 2025, 2026 y 2027", "AUDITOR", "VOTABLE"),
 ("6", None, "Reelección de Dª. Alexandra Reich como consejera dominical, por el plazo estatutario", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7", None, "Delegación en el Consejo de Administración de la facultad de aumentar el capital social", "SHARE_ISSUANCE", "VOTABLE"),
 ("8", None, "Delegación en el Consejo de Administración de la facultad de emitir bonos, obligaciones y demás valores de renta fija convertibles", "BONDS", "VOTABLE"),
 ("9", None, "Delegación de facultades para la formalización de todos los acuerdos adoptados por la Junta General", "POWERS", "VOTABLE"),
 ("10", None, "Votación con carácter consultivo del informe anual sobre remuneraciones de los Consejeros, correspondiente al ejercicio 2023", "REMUNERATION_REPORT", "VOTABLE"),
]),

("ES0109067019", "2024-06-05",
 "https://www.cnmv.es/webservices/verdocumento/ver?t=%7B15ef24ed-9eea-4375-b192-d86055ecad4d%7D",
 "CNMV OIR acuerdos JGA Amadeus 2024", [
 ("1", None, "Examen y aprobación de las Cuentas Anuales e Informe de Gestión de la Sociedad, Cuentas Anuales consolidadas e Informe de Gestión consolidado de su Grupo, ejercicio 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("2", None, "Examen y aprobación del estado de información no financiera del ejercicio 2023", "EINF", "VOTABLE"),
 ("3", None, "Informe anual sobre las remuneraciones de los Consejeros 2023 para su votación con carácter consultivo", "REMUNERATION_REPORT", "VOTABLE"),
 ("4", None, "Aprobación de la propuesta de aplicación de resultado y otras reservas de la Sociedad del ejercicio 2023", "ALLOCATION", "VOTABLE"),
 ("5", None, "Examen y aprobación de la gestión desarrollada por el Consejo de Administración del ejercicio 2023", "DISCHARGE", "VOTABLE"),
 ("6.1", "6", "Reelección de D. William Connelly como Consejero independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6.2", "6", "Reelección de D. Luis Maroto Camino como Consejero ejecutivo por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6.3", "6", "Reelección de Dña. Pilar García Ceballos-Zúñiga como Consejera independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6.4", "6", "Reelección de D. Stephan Gemkow como Consejero independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6.5", "6", "Reelección de D. Peter Kürpick como Consejero independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6.6", "6", "Reelección de Dña. Xiaoqun Clever-Steg como Consejera independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6.7", "6", "Reelección de Dña. Amanda Mesler como Consejera independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6.8", "6", "Reelección de Dña. Jana Eggers como Consejera independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7", None, "Aprobación de la retribución de los miembros del Consejo de Administración, en su condición de tales", "REMUNERATION_POLICY", "VOTABLE"),
 ("8", None, "Aprobación de la Política de Remuneraciones de los Consejeros (2025-2027)", "REMUNERATION_POLICY", "VOTABLE"),
 ("9", None, "Aprobación de la participación de los Consejeros Ejecutivos en el Plan de Acciones de Amadeus", "LTIP", "VOTABLE"),
 ("10", None, "Delegación de facultades en el Consejo de Administración, con facultad de sustitución", "POWERS", "VOTABLE"),
]),

("ES0109067019", "2025-06-03", B + "BORME-C-2025-1470", "BORME-C-2025-1470", [
 ("1", None, "Examen y aprobación de las Cuentas Anuales e Informe de Gestión de la Sociedad, Cuentas Anuales consolidadas e Informe de Gestión consolidado, ejercicio 2024", "ACCOUNTS_GROUP", "VOTABLE"),
 ("2", None, "Examen y aprobación del Estado de Información No Financiera e información sobre sostenibilidad del ejercicio 2024", "EINF", "VOTABLE"),
 ("3", None, "Informe anual sobre las remuneraciones de los Consejeros 2024 para su votación con carácter consultivo", "REMUNERATION_REPORT", "VOTABLE"),
 ("4", None, "Aprobación de la propuesta de aplicación de resultado y otras reservas de la Sociedad del ejercicio 2024", "ALLOCATION", "VOTABLE"),
 ("5", None, "Examen y aprobación de la gestión desarrollada por el Consejo de Administración del ejercicio 2024", "DISCHARGE", "VOTABLE"),
 ("6", None, "Fijación del número de puestos en el Consejo de Administración", "BOARD", "VOTABLE"),
 ("7.1", "7", "Nombramiento de Don Leo Puri como Consejero independiente por un periodo de tres años", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7.2", "7", "Reelección de Don William Connelly como Consejero independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7.3", "7", "Reelección de Don Luis Maroto Camino como Consejero ejecutivo por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7.4", "7", "Reelección de Doña Pilar García Ceballos-Zúñiga como Consejera independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7.5", "7", "Reelección de Don Stephan Gemkow como Consejero independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7.6", "7", "Reelección de Don Peter Kürpick como Consejero independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7.7", "7", "Reelección de Doña Xiaoqun Clever-Steg como Consejera independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7.8", "7", "Reelección de Doña Amanda Mesler como Consejera independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7.9", "7", "Reelección de Doña Jana Eggers como Consejera independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7.10", "7", "Reelección de Doña Eriikka Söderström como Consejera independiente por un período de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7.11", "7", "Reelección de Don David Vegara Figueras como Consejero independiente por un periodo de un año", "DIRECTOR_ELECTION", "VOTABLE"),
 ("8", None, "Renovación del nombramiento de auditores de la Sociedad y de su Grupo consolidado para los ejercicios 2025 y 2026", "AUDITOR", "VOTABLE"),
 ("9", None, "Delegación de facultades en el Consejo de Administración, con facultad de sustitución", "POWERS", "VOTABLE"),
]),

("ES0121975009", "2024-06-15", B + "BORME-C-2024-2142", "BORME-C-2024-2142", [
 ("1", None, "Aprobación de las cuentas anuales e informe de gestión de CAF y de su grupo consolidado, ejercicio 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("2", None, "Aprobación de la gestión del Consejo de Administración durante el ejercicio 2023", "DISCHARGE", "VOTABLE"),
 ("3", None, "Aprobación del Estado de Información no Financiera – Informe de Sostenibilidad consolidado del ejercicio 2023", "EINF", "VOTABLE"),
 ("4", None, "Aprobación de la propuesta de aplicación del resultado del ejercicio 2023, con distribución de dividendos de 1,11 euros por acción", "ALLOCATION", "VOTABLE"),
 ("5", None, "Reelección de auditores de cuentas para los ejercicios 2024, 2025 y 2026", "AUDITOR", "VOTABLE"),
 ("6.1", "6", "Reelección de Doña Idoia Zenarrutzabeitia Beldarrain como Consejera Dominical", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6.2", "6", "Reelección de Doña Marta Baztarrica Lizarbe como Consejera Ejecutiva", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6.3", "6", "Reelección de Doña Carmen Allo Pérez como Consejera Independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6.4", "6", "Reelección de Don Manuel Domínguez de la Maza como Consejero Dominical", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6.5", "6", "Fijación del número de consejeros en once (11) miembros", "BOARD", "VOTABLE"),
 ("7", None, "Modificación del artículo 39 de los Estatutos Sociales", "ARTICLES_AMEND", "VOTABLE"),
 ("8", None, "Aprobación de la Política de Remuneraciones de los Consejeros aplicable a los ejercicios 2024, 2025 y 2026", "REMUNERATION_POLICY", "VOTABLE"),
 ("9", None, "Votación consultiva del Informe Anual sobre Remuneraciones de los Consejeros del ejercicio 2023", "REMUNERATION_REPORT", "VOTABLE"),
 ("10", None, "Delegación de facultades al Consejo de Administración para la formalización y ejecución de los anteriores acuerdos", "POWERS", "VOTABLE"),
]),

("ES0105025003", "2024-05-08",
 "https://ir.merlinproperties.com/wp-content/uploads/2024/05/MERLIN-OIR-JGA-2024.pdf",
 "Merlin OIR convocatoria JGA 2024 (issuer)", [
 ("1", None, "Examen y aprobación de las cuentas anuales y del informe de gestión de Merlin Properties, SOCIMI, S.A. y de su grupo consolidado, ejercicio 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("2.1", "2", "Examen y aprobación de la propuesta de aplicación del resultado del ejercicio 2023", "ALLOCATION", "VOTABLE"),
 ("2.2", "2", "Examen y aprobación de una distribución de dividendo con cargo a la reserva de prima de emisión", "DIVIDEND", "VOTABLE"),
 ("3", None, "Examen y aprobación de la gestión desarrollada por el Consejo de Administración durante el ejercicio 2023", "DISCHARGE", "VOTABLE"),
 ("4.1", "4", "Fijación en catorce (14) el número de miembros del Consejo de Administración", "BOARD", "VOTABLE"),
 ("4.2", "4", "Reelección de don Ismael Clemente Orrego, como consejero ejecutivo", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.3", "4", "Reelección de don Miguel Ollero Barrera, como consejero dominical", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.4", "4", "Reelección de doña María Luisa Jordá Castro, como consejera independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.5", "4", "Reelección de doña Ana María García Fau, como consejera independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.6", "4", "Reelección de don Fernando Javier Ortiz Vaamonde, como consejero dominical", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.7", "4", "Reelección de don George Donald Johnston, como consejero independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.8", "4", "Reelección de don Emilio Novela Berlín, como consejero independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.9", "4", "Ratificación del nombramiento por cooptación y reelección de don Juan María Aguirre Gonzalo, como consejero dominical", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.10", "4", "Nombramiento de doña Inès Archer Toper, como consejera independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("4.11", "4", "Nombramiento de doña Julia Bayón Pedraza, como consejera independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("5", None, "Votación consultiva del Informe Anual sobre Remuneraciones de los Consejeros y del Apéndice Estadístico, ejercicio 2023", "REMUNERATION_REPORT", "VOTABLE"),
 ("6", None, "Modificación del Artículo 41 de los Estatutos Sociales (Desarrollo de la Junta General de Accionistas)", "ARTICLES_AMEND", "VOTABLE"),
 ("7", None, "Autorización para la reducción del plazo de la convocatoria de las Juntas Generales Extraordinarias", "MEETING_FORMALITY", "VOTABLE"),
 ("8", None, "Autorización al Consejo de Administración para la interpretación, subsanación, complemento, ejecución y desarrollo de los acuerdos", "POWERS", "VOTABLE"),
]),

("ES0173093024", "2024-06-03",
 "https://www.redeia.com/sites/default/files/06_ACCIONISTAS/Documentos/Hechos_relevantes/2024/20240430_HR_ConvocatoriaJunta_ES.pdf",
 "Redeia convocatoria JGA 2024 (issuer/CNMV OIR)", [
 ("1", None, "Examen y aprobación de las Cuentas Anuales y del Informe de Gestión de Redeia Corporación, S.A., ejercicio 2023", "ACCOUNTS_SOLO", "VOTABLE"),
 ("2", None, "Examen y aprobación de las Cuentas Anuales Consolidadas y del Informe de Gestión Consolidado del Grupo de Redeia Corporación, S.A., ejercicio 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("3", None, "Examen y aprobación de la propuesta de aplicación del resultado del ejercicio 2023 y distribución de dividendos", "ALLOCATION", "VOTABLE"),
 ("4", None, "Examen y aprobación del informe sobre la información no financiera del Grupo Consolidado de Redeia Corporación, S.A., ejercicio 2023", "EINF", "VOTABLE"),
 ("5", None, "Examen y aprobación de la gestión desarrollada por el Consejo de Administración de Redeia Corporación, S.A. durante el ejercicio 2023", "DISCHARGE", "VOTABLE"),
 ("6.1", "6", "Reelección como consejera, categoría otros externos, de Dª. Beatriz Corredor Sierra", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6.2", "6", "Reelección como consejero ejecutivo de D. Roberto García Merino", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6.3", "6", "Nombramiento como consejera independiente de Dª. Guadalupe de la Mata Muñoz", "DIRECTOR_ELECTION", "VOTABLE"),
 ("7", None, "Delegación a favor del Consejo de Administración, por cinco años, de la facultad de aumentar el capital social hasta 135.270.000 euros", "SHARE_ISSUANCE", "VOTABLE"),
 ("8", None, "Delegación a favor del Consejo de Administración, por cinco años y límite de 5.000 millones de euros, de la facultad de emitir obligaciones, bonos y otros instrumentos de renta fija", "BONDS", "VOTABLE"),
 ("9.1", "9", "Autorización para la adquisición derivativa de acciones propias por la Sociedad o sociedades del grupo", "BUYBACK", "VOTABLE"),
 ("9.2", "9", "Aprobación de un Plan de Retribución dirigido a empleados, consejeros ejecutivos y miembros de la dirección", "LTIP", "VOTABLE"),
 ("9.3", "9", "Revocación de las autorizaciones anteriores", "BUYBACK", "VOTABLE"),
 ("10.1", "10", "Aprobación del Informe Anual sobre Remuneraciones de los Consejeros 2023 de Redeia Corporación, S.A.", "REMUNERATION_REPORT", "VOTABLE"),
 ("10.2", "10", "Aprobación de la remuneración del Consejo de Administración de Redeia Corporación, S.A., para el ejercicio 2024", "REMUNERATION_POLICY", "VOTABLE"),
 ("10.3", "10", "Aprobación de la Política de Remuneración de los miembros del Consejo de Administración para 2025-2027", "REMUNERATION_POLICY", "VOTABLE"),
 ("11", None, "Delegación para la plena ejecución de los acuerdos adoptados en la Junta General", "POWERS", "VOTABLE"),
 ("12", None, "Información a la Junta General sobre el Informe Anual de Gobierno Corporativo de Redeia, ejercicio 2023", "BOARD_REGULATIONS", "INFORMATION_ONLY"),
 ("13", None, "Información a la Junta General sobre el Informe Anual de Sostenibilidad de Redeia, ejercicio 2023", "EINF", "INFORMATION_ONLY"),
]),

("ES0173516115", "2024-05-09", B + "BORME-C-2024-983", "BORME-C-2024-983", [
 ("1", None, "Examen y aprobación de las Cuentas Anuales e Informe de Gestión de Repsol, S.A. y de las Cuentas Anuales Consolidadas y del Informe de Gestión Consolidado, ejercicio 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("2", None, "Examen y aprobación de la propuesta de aplicación del resultado del ejercicio 2023", "ALLOCATION", "VOTABLE"),
 ("3", None, "Examen y aprobación del Estado de Información No Financiera del ejercicio 2023", "EINF", "VOTABLE"),
 ("4", None, "Examen y aprobación de la gestión del Consejo de Administración de Repsol, S.A., ejercicio 2023", "DISCHARGE", "VOTABLE"),
 ("5", None, "Designación de Auditor de Cuentas de Repsol, S.A. y de su Grupo Consolidado para el ejercicio 2024", "AUDITOR", "VOTABLE"),
 ("6", None, "Reparto de la cantidad fija de 0,45 euros brutos por acción con cargo a reservas libres", "DIVIDEND", "VOTABLE"),
 ("7", None, "Aprobación de una reducción de capital social por un importe de 40.000.000 de euros, mediante amortización de acciones propias", "CAPITAL_REDUCTION", "VOTABLE"),
 ("8", None, "Aprobación de una reducción de capital social por un importe máximo de 121.739.605 euros, equivalente al 10% del capital", "CAPITAL_REDUCTION", "VOTABLE"),
 ("9", None, "Votación consultiva del Informe Anual sobre Remuneraciones de los Consejeros de Repsol, S.A. del ejercicio 2023", "REMUNERATION_REPORT", "VOTABLE"),
 ("10", None, "Votación consultiva sobre la estrategia de transición energética de la Compañía", "CLIMATE", "VOTABLE"),
 ("11", None, "Delegación de facultades para interpretar, complementar, desarrollar, ejecutar, subsanar y formalizar los acuerdos", "POWERS", "VOTABLE"),
]),

("ES0173516115", "2025-05-29",
 "https://www.repsol.com/content/dam/repsol-corporate/es/accionistas-e-inversores/informes-jga/2025/convocatoria-junta-general-accionistas-2025.pdf",
 "Repsol convocatoria JGA 2025 (issuer)", [
 ("1", None, "Examen y aprobación de las Cuentas Anuales e Informe de Gestión de Repsol, S.A. y de las Cuentas Anuales Consolidadas y del Informe de Gestión Consolidado, ejercicio 2024", "ACCOUNTS_GROUP", "VOTABLE"),
 ("2", None, "Examen y aprobación de la propuesta de aplicación del resultado del ejercicio 2024", "ALLOCATION", "VOTABLE"),
 ("3", None, "Examen y aprobación del Estado de Información No Financiera del ejercicio 2024", "EINF", "VOTABLE"),
 ("4", None, "Examen y aprobación de la gestión del Consejo de Administración de Repsol, S.A., ejercicio 2024", "DISCHARGE", "VOTABLE"),
 ("5", None, "Designación de Auditor de Cuentas de Repsol, S.A. y de su Grupo Consolidado para el ejercicio 2025", "AUDITOR", "VOTABLE"),
 ("6", None, "Reparto en julio de 2025 de la cantidad fija de 0,5 euros brutos por acción con cargo a reservas libres", "DIVIDEND", "VOTABLE"),
 ("7", None, "Reparto en enero de 2026 de la cantidad fija de 0,5 euros brutos por acción con cargo a reservas libres", "DIVIDEND", "VOTABLE"),
 ("8", None, "Aprobación de una reducción de capital social por un importe determinable mediante amortización de acciones propias", "CAPITAL_REDUCTION", "VOTABLE"),
 ("9", None, "Aprobación de una reducción de capital social por un importe máximo de 115.739.605 euros, equivalente al 10% del capital", "CAPITAL_REDUCTION", "VOTABLE"),
 ("10", None, "Delegación en el Consejo de Administración de la facultad para emitir valores de renta fija, convertibles o canjeables, por hasta 5.000 millones de euros", "BONDS", "VOTABLE"),
 ("11", None, "Reelección como Consejera de Dña. Aurora Catá Sala", "DIRECTOR_ELECTION", "VOTABLE"),
 ("12", None, "Reelección como Consejera de Dña. Isabel Torremocha Ferrezuelo", "DIRECTOR_ELECTION", "VOTABLE"),
 ("13", None, "Reelección como Consejero de D. Mariano Marzo Carpio", "DIRECTOR_ELECTION", "VOTABLE"),
 ("14", None, "Votación consultiva del Informe Anual sobre Remuneraciones de los Consejeros de Repsol, S.A. del ejercicio 2024", "REMUNERATION_REPORT", "VOTABLE"),
 ("15", None, "Examen y aprobación de la Política de Remuneraciones de los Consejeros de Repsol, S.A. (2025-2028)", "REMUNERATION_POLICY", "VOTABLE"),
 ("16", None, "Modificación del Programa de Incentivo a Largo Plazo 2025-2028", "LTIP", "VOTABLE"),
 ("17", None, "Aprobación de tres nuevos ciclos adicionales del Programa de Incentivo a Largo Plazo", "LTIP", "VOTABLE"),
 ("18", None, "Delegación de facultades para interpretar, complementar, desarrollar, ejecutar, subsanar y formalizar los acuerdos", "POWERS", "VOTABLE"),
]),

("ES0178430E18", "2024-04-11",
 "https://www.telefonica.com/es/wp-content/uploads/sites/4/2024/03/jga24-convocatoria-orden-del-dia.pdf",
 "Telefónica convocatoria JGA 2024 (issuer)", [
 ("I.1", "I", "Aprobación de las Cuentas Anuales y del Informe de Gestión tanto de Telefónica, S.A. como de su Grupo Consolidado, ejercicio 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("I.2", "I", "Aprobación del Estado de Información no Financiera del Grupo Consolidado encabezado por Telefónica, S.A., ejercicio 2023", "EINF", "VOTABLE"),
 ("I.3", "I", "Aprobación de la gestión del Consejo de Administración de Telefónica, S.A. durante el ejercicio 2023", "DISCHARGE", "VOTABLE"),
 ("II", None, "Aprobación de la Propuesta de Aplicación del Resultado de Telefónica, S.A. del ejercicio 2023", "ALLOCATION", "VOTABLE"),
 ("III", None, "Reelección del Auditor de Cuentas para el ejercicio 2024", "AUDITOR", "VOTABLE"),
 ("IV.1", "IV", "Reelección de D. Isidro Fainé Casas como Consejero Dominical", "DIRECTOR_ELECTION", "VOTABLE"),
 ("IV.2", "IV", "Reelección de D. José Javier Echenique Landiríbar como Consejero Independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("IV.3", "IV", "Reelección de D. Peter Löscher como Consejero Independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("IV.4", "IV", "Reelección de Dª Verónica María Pascual Boé como Consejera Independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("IV.5", "IV", "Reelección de Dª Claudia Sender Ramírez como Consejera Independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("IV.6", "IV", "Ratificación y nombramiento de Dª Solange Sobral Targa como Consejera Independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("IV.7", "IV", "Ratificación y nombramiento de D. Alejandro Reynal Ample como Consejero Independiente", "DIRECTOR_ELECTION", "VOTABLE"),
 ("V", None, "Reducción del capital social mediante la amortización de acciones propias, con exclusión del derecho de oposición de acreedores", "CAPITAL_REDUCTION", "VOTABLE"),
 ("VI", None, "Retribución al accionista. Distribución de dividendos con cargo a reservas de libre disposición", "DIVIDEND", "VOTABLE"),
 ("VII", None, "Aprobación de un Plan de Incentivo a Largo Plazo consistente en la entrega de acciones de Telefónica destinado a directivos del Grupo", "LTIP", "VOTABLE"),
 ("VIII", None, "Delegación de facultades para formalizar, interpretar, subsanar y ejecutar los acuerdos adoptados por la Junta General", "POWERS", "VOTABLE"),
 ("IX", None, "Votación consultiva del Informe Anual 2023 sobre Remuneraciones de los Consejeros de Telefónica, S.A.", "REMUNERATION_REPORT", "VOTABLE"),
]),

("ES0125220311", "2025-06-25",
 "https://www.acciona.com/content/dam/acciona-global/documentos/juntas-generales/2025/en/2-ana-proposed-resolutions-agm-2025.pdf",
 "Acciona proposed resolutions AGM 2025 (issuer)", [
 ("1.1", "1", "Examination and approval of the individual annual accounts of Acciona, S.A. for financial year 2024", "ACCOUNTS_SOLO", "VOTABLE"),
 ("1.2", "1", "Examination and approval of the individual management report of Acciona, S.A. for financial year 2024", "ACCOUNTS_SOLO", "VOTABLE"),
 ("1.3", "1", "Approval of the corporate management and actions carried out by the Board of Directors of Acciona, S.A. during 2024", "DISCHARGE", "VOTABLE"),
 ("1.4", "1", "Examination and approval of the consolidated non-financial information statement of Acciona, S.A. and its group, 2024", "EINF", "VOTABLE"),
 ("1.5", "1", "Application of the results of financial year 2024", "ALLOCATION", "VOTABLE"),
 ("1.6", "1", "Re-election of KPMG Auditores, S.L. as auditors of Acciona, S.A. and its consolidated group for 2025", "AUDITOR", "VOTABLE"),
 ("2.1", "2", "Re-elect Ms. Sonia Dulá as Independent Director", "DIRECTOR_ELECTION", "VOTABLE"),
 ("2.2", "2", "Re-elect Ms. Maite Arango García-Urtiaga as Independent Director", "DIRECTOR_ELECTION", "VOTABLE"),
 ("2.3", "2", "Re-elect Mr. Carlo Clavarino as Independent Director", "DIRECTOR_ELECTION", "VOTABLE"),
 ("3", None, "Approval of the Directors' Remuneration Policy for financial years 2026, 2027 and 2028", "REMUNERATION_POLICY", "VOTABLE"),
 ("4", None, "Advisory vote on the Annual Directors' Remuneration Report for 2024", "REMUNERATION_REPORT", "VOTABLE"),
 ("5", None, "Authorisation to convene Extraordinary General Meetings with a minimum notice of fifteen days", "MEETING_FORMALITY", "VOTABLE"),
 ("6", None, "Delegation of powers to the Board of Directors for the implementation, interpretation, remedy and formalisation of the resolutions", "POWERS", "VOTABLE"),
]),

("ES0118900010", "2024-04-11",
 "https://static.ferrovial.com/wp-content/uploads/2024/02/28202914/notice-agenda-and-explanatory-notes-agm-2024-esp.pdf",
 "Ferrovial SE notice & agenda AGM 2024 (issuer)", [
 ("1", None, "Apertura", "MEETING_FORMALITY", "INFORMATION_ONLY"),
 ("2a", "2", "Informe del Consejo del ejercicio 2023 (discusión)", "ACCOUNTS_GROUP", "INFORMATION_ONLY"),
 ("2b", "2", "Política de aportaciones a reservas y dividendos (discusión)", "ALLOCATION", "INFORMATION_ONLY"),
 ("2c", "2", "Estructura de gobierno corporativo y cumplimiento del Código neerlandés de Gobierno Corporativo (discusión)", "BOARD_REGULATIONS", "INFORMATION_ONLY"),
 ("2d", "2", "Informe de remuneraciones del ejercicio 2023 (punto para votación consultiva)", "REMUNERATION_REPORT", "VOTABLE"),
 ("2e", "2", "Aprobación de las cuentas anuales del ejercicio 2023 (punto para votación)", "ACCOUNTS_GROUP", "VOTABLE"),
 ("3", None, "Informe de Estrategia Climática del ejercicio 2023 (punto para votación consultiva)", "CLIMATE", "VOTABLE"),
 ("4", None, "Aprobación de la gestión de los Consejeros en el ejercicio de sus funciones durante el ejercicio 2023 (punto para votación)", "DISCHARGE", "VOTABLE"),
 ("5", None, "Reelección de Ernst & Young Accountants LLP como auditor externo de la Sociedad para el ejercicio 2024 (punto para votación)", "AUDITOR", "VOTABLE"),
 ("6a", "6", "Autorización al Consejo para emitir acciones ordinarias para fines generales (punto para votación)", "SHARE_ISSUANCE", "VOTABLE"),
 ("6b", "6", "Autorización al Consejo para emitir acciones ordinarias a efectos del dividendo flexible (punto para votación)", "SHARE_ISSUANCE", "VOTABLE"),
 ("7a", "7", "Autorización al Consejo para limitar o excluir el derecho de suscripción preferente de acciones ordinarias para fines generales (punto para votación)", "SHARE_ISSUANCE", "VOTABLE"),
 ("7b", "7", "Autorización al Consejo para limitar o excluir el derecho de suscripción preferente de acciones ordinarias a efectos del dividendo flexible (punto para votación)", "SHARE_ISSUANCE", "VOTABLE"),
 ("8", None, "Autorización al Consejo para adquirir acciones ordinarias (punto para votación)", "BUYBACK", "VOTABLE"),
 ("9", None, "Amortización de acciones ordinarias (punto para votación)", "CAPITAL_REDUCTION", "VOTABLE"),
 ("10", None, "Cierre", "MEETING_FORMALITY", "INFORMATION_ONLY"),
]),

("ES0118900010", "2025-04-24",
 "https://www.cnmv.es/webservices/verdocumento/ver?t=%7Ba38bc8f8-7792-4f32-b7eb-26c2c99714a6%7D",
 "CNMV OIR convocatoria JGA Ferrovial 2025", [
 ("1", None, "Apertura", "MEETING_FORMALITY", "INFORMATION_ONLY"),
 ("2a", "2", "Informe del Consejo de Administración sobre el desempeño financiero y no financiero (ESG) del ejercicio 2024 (discusión)", "ACCOUNTS_GROUP", "INFORMATION_ONLY"),
 ("2b", "2", "Política de aportaciones a reservas y dividendos (discusión)", "ALLOCATION", "INFORMATION_ONLY"),
 ("2c", "2", "Informe de remuneraciones del ejercicio 2024 (votación consultiva)", "REMUNERATION_REPORT", "VOTABLE"),
 ("2d", "2", "Aprobación de las cuentas anuales del ejercicio 2024 (punto para votación)", "ACCOUNTS_GROUP", "VOTABLE"),
 ("3", None, "Informe de Estrategia Climática del ejercicio 2024 (votación consultiva)", "CLIMATE", "VOTABLE"),
 ("4", None, "Aprobación de la gestión de los Consejeros en el ejercicio de sus funciones durante el ejercicio 2024 (punto para votación)", "DISCHARGE", "VOTABLE"),
 ("5a", "5", "Propuesta de reelección de D. Rafael del Pino y Calvo-Sotelo como Consejero Ejecutivo (punto para votación)", "DIRECTOR_ELECTION", "VOTABLE"),
 ("5b", "5", "Propuesta de reelección de D. Óscar Fanjul Martín como Consejero No Ejecutivo (punto para votación)", "DIRECTOR_ELECTION", "VOTABLE"),
 ("5c", "5", "Propuesta de reelección de Dña. María del Pino y Calvo-Sotelo como Consejera No Ejecutiva (punto para votación)", "DIRECTOR_ELECTION", "VOTABLE"),
 ("5d", "5", "Propuesta de reelección de D. José Fernando Sánchez-Junco Mans como Consejero No Ejecutivo (punto para votación)", "DIRECTOR_ELECTION", "VOTABLE"),
 ("5e", "5", "Propuesta de reelección de D. Bruno Vito Benito Di Leo Allen como Consejero No Ejecutivo (punto para votación)", "DIRECTOR_ELECTION", "VOTABLE"),
 ("5f", "5", "Propuesta de reelección de Dña. Hildegard Maria Wortmann como Consejera No Ejecutiva (punto para votación)", "DIRECTOR_ELECTION", "VOTABLE"),
 ("5g", "5", "Propuesta de reelección de Dña. Alicia Reyes Revuelta como Consejera No Ejecutiva (punto para votación)", "DIRECTOR_ELECTION", "VOTABLE"),
 ("6", None, "Modificación de la Política de Remuneraciones de los Consejeros (punto para votación)", "REMUNERATION_POLICY", "VOTABLE"),
 ("7a", "7", "Propuesta de nombramiento de PriceWaterhouseCoopers Accountants N.V. como auditor externo para los ejercicios 2025-2027 (punto para votación)", "AUDITOR", "VOTABLE"),
 ("7b", "7", "Propuesta de nombramiento de PriceWaterhouseCoopers Accountants N.V. como verificador de la información sobre sostenibilidad 2025-2027 (punto para votación)", "AUDITOR", "VOTABLE"),
 ("8a", "8", "Autorización al Consejo de Administración para emitir acciones ordinarias con fines generales (punto para votación)", "SHARE_ISSUANCE", "VOTABLE"),
 ("8b", "8", "Autorización al Consejo de Administración para emitir acciones ordinarias a efectos del dividendo flexible (punto para votación)", "SHARE_ISSUANCE", "VOTABLE"),
 ("9a", "9", "Autorización al Consejo de Administración para limitar o excluir el derecho de suscripción preferente con fines generales (punto para votación)", "SHARE_ISSUANCE", "VOTABLE"),
 ("9b", "9", "Autorización al Consejo de Administración para limitar o excluir el derecho de suscripción preferente a efectos del dividendo flexible (punto para votación)", "SHARE_ISSUANCE", "VOTABLE"),
 ("10", None, "Autorización al Consejo de Administración para adquirir acciones ordinarias (punto para votación)", "BUYBACK", "VOTABLE"),
 ("11", None, "Amortización de acciones ordinarias (punto para votación)", "CAPITAL_REDUCTION", "VOTABLE"),
 ("12", None, "Cierre", "MEETING_FORMALITY", "INFORMATION_ONLY"),
]),

("NL0000235190", "2024-04-10",
 "https://www.airbus.com/sites/g/files/jlcbta136/files/2024-04/Airbus%20AGM%202024%20-%20Minutes%20-%20Extract.pdf",
 "Airbus SE AGM 2024 minutes extract (issuer)", [
 ("1", None, "Adoption of the audited accounts for the financial year 2023", "ACCOUNTS_GROUP", "VOTABLE"),
 ("2", None, "Approval of the result allocation and distribution of an ordinary dividend for the financial year 2023", "ALLOCATION", "VOTABLE"),
 ("3", None, "Approval of an extraordinary dividend for the financial year 2023", "DIVIDEND", "VOTABLE"),
 ("4", None, "Release from liability of the Non-Executive Members of the Board of Directors", "DISCHARGE", "VOTABLE"),
 ("5", None, "Release from liability of the Executive Member of the Board of Directors", "DISCHARGE", "VOTABLE"),
 ("6", None, "Reappointment of Ernst & Young Accountants LLP as auditor for the financial year 2024", "AUDITOR", "VOTABLE"),
 ("7", None, "Approval, as an advisory vote, of the implementation of the Remuneration Policy for the financial year 2023", "REMUNERATION_REPORT", "VOTABLE"),
 ("8", None, "Adoption of the Board of Directors' Remuneration Policy", "REMUNERATION_POLICY", "VOTABLE"),
 ("9", None, "Reappointment of Mr Rene Obermann as Non-Executive Member of the Board of Directors for a term of three years", "DIRECTOR_ELECTION", "VOTABLE"),
 ("10", None, "Reappointment of Mr Victor Chu as Non-Executive Member of the Board of Directors for a term of three years", "DIRECTOR_ELECTION", "VOTABLE"),
 ("11", None, "Reappointment of Mr Jean-Pierre Clamadieu as Non-Executive Member of the Board of Directors for a term of three years", "DIRECTOR_ELECTION", "VOTABLE"),
 ("12", None, "Reappointment of Ms Amparo Moraleda as Non-Executive Member of the Board of Directors for a term of three years", "DIRECTOR_ELECTION", "VOTABLE"),
 ("13", None, "Appointment of Dr Feiyu Xu as Non-Executive Member of the Board of Directors for a term of two years, in replacement of Mr Ralph D. Crosby, Jr.", "DIRECTOR_ELECTION", "VOTABLE"),
 ("14", None, "Delegation to the Board of Directors of powers to issue shares and grant rights to subscribe for shares for employee share ownership plans and share-related long-term incentive plans", "SHARE_ISSUANCE", "VOTABLE"),
 ("15", None, "Delegation to the Board of Directors of powers to issue shares and grant rights to subscribe for shares for funding or any other corporate purpose", "SHARE_ISSUANCE", "VOTABLE"),
 ("16", None, "Renewal of the authorisation for the Board of Directors to repurchase up to 10% of the Company's issued share capital", "BUYBACK", "VOTABLE"),
 ("17", None, "Cancellation of shares repurchased by the Company", "CAPITAL_REDUCTION", "VOTABLE"),
]),

("NL0000235190", "2025-04-15",
 "https://www.airbus.com/sites/g/files/jlcbta136/files/2025-03/convening_notice_0.pdf",
 "Airbus SE convening notice AGM 2025 (issuer)", [
 ("1", None, "Adoption of the audited accounts for the financial year 2024", "ACCOUNTS_GROUP", "VOTABLE"),
 ("2", None, "Approval of the result allocation and distribution of a dividend for the financial year 2024", "ALLOCATION", "VOTABLE"),
 ("3", None, "Approval of an extraordinary dividend for the financial year 2024", "DIVIDEND", "VOTABLE"),
 ("4", None, "Release from liability of the Non-Executive Members of the Board of Directors", "DISCHARGE", "VOTABLE"),
 ("5", None, "Release from liability of the Executive Member of the Board of Directors", "DISCHARGE", "VOTABLE"),
 ("6", None, "Reappointment of EY Accountants B.V. as auditor for the financial year 2025", "AUDITOR", "VOTABLE"),
 ("7", None, "Appointment of KPMG Accountants N.V. as auditor for the financial year 2026", "AUDITOR", "VOTABLE"),
 ("8", None, "Approval, as an advisory vote, of the implementation of the Remuneration Policy for the financial year 2024", "REMUNERATION_REPORT", "VOTABLE"),
 ("9", None, "Adoption of the Board of Directors' Remuneration Policy", "REMUNERATION_POLICY", "VOTABLE"),
 ("10", None, "Reappointment of Mr Guillaume Faury as Executive Member of the Board of Directors for a term of three years", "DIRECTOR_ELECTION", "VOTABLE"),
 ("11", None, "Reappointment of Ms Catherine Guillouard as Non-Executive Member of the Board of Directors for a term of three years", "DIRECTOR_ELECTION", "VOTABLE"),
 ("12", None, "Reappointment of Ms Irene Rummelhoff as Non-Executive Member of the Board of Directors for a term of three years", "DIRECTOR_ELECTION", "VOTABLE"),
 ("13", None, "Appointment of Dr Doris Höpke as Non-Executive Member of the Board of Directors for a term of three years", "DIRECTOR_ELECTION", "VOTABLE"),
 ("14", None, "Delegation to the Board of Directors of powers to issue shares and grant rights to subscribe for shares for employee share ownership plans and share-related long-term incentive plans", "SHARE_ISSUANCE", "VOTABLE"),
 ("15", None, "Delegation to the Board of Directors of powers to issue shares and grant rights to subscribe for shares for funding or any other corporate purpose", "SHARE_ISSUANCE", "VOTABLE"),
 ("16", None, "Renewal of the authorisation for the Board of Directors to repurchase up to 10% of the Company's issued share capital", "BUYBACK", "VOTABLE"),
 ("17", None, "Cancellation of shares repurchased by the Company", "CAPITAL_REDUCTION", "VOTABLE"),
]),
]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    total_items = 0
    for isin, date, url, ref, items in M:
        path = OUT / f"{isin}_{date}.csv"
        with path.open("w", newline="", encoding="utf-8") as f:
            w = csv.writer(f)
            w.writerow(["isin", "meeting_date", "item_number", "parent_item",
                        "item_order", "title_es", "title_en", "concept_id",
                        "votable_status", "source_url", "source_ref",
                        "retrieved_at"])
            for i, (num, parent, title, concept, vot) in enumerate(items, 1):
                w.writerow([isin, date, num, parent or "", i, title, "",
                            concept, vot, url, ref, RETRIEVED])
        total_items += len(items)
        print(f"{isin} {date}: {len(items)} items -> {path.name}")
    print(f"TOTAL: {len(M)} meetings, {total_items} agenda items")


if __name__ == "__main__":
    main()
