"""G9 preview: size the same-meeting / same-proposal reconciliation problem.

Measures — for meetings where MAPFRE and SEC N-PX both voted — how many
proposal instances can already be paired by item number or text, before
any semantic matching is attempted. Output only; no matching applied.

    uv run python scripts/g9_preview.py
"""
from __future__ import annotations

from pathlib import Path

import duckdb
import pyarrow as pa
import pyarrow.parquet as pq

REPO = Path(__file__).resolve().parents[1]
GOLD = REPO / "data" / "gold" / "votes.duckdb"
OUT_PQ = REPO / "reports" / "g9-reconciliation-corpus.parquet"
OUT_MD = REPO / "docs" / "findings" / "G9-PREVIEW.md"


def main() -> None:
    con = duckdb.connect(str(GOLD), read_only=True)

    # meetings observed by both sources
    shared = con.execute("""
        SELECT m.meeting_id, i.canonical_name issuer, m.meeting_date
        FROM meetings m JOIN issuers i USING (issuer_id)
        WHERE EXISTS (SELECT 1 FROM proposals p JOIN votes v USING (proposal_id)
                      WHERE p.meeting_id=m.meeting_id AND v.source_id='mapfre_am')
          AND EXISTS (SELECT 1 FROM proposals p JOIN votes v USING (proposal_id)
                      WHERE p.meeting_id=m.meeting_id AND v.source_id='sec_npx')
        ORDER BY 1""").fetchall()

    # proposal instances per side (raw texts + numbers)
    insts = con.execute("""
        SELECT pi.proposal_id, pi.source_id, pi.text_raw,
               p.proposal_number, p.meeting_id
        FROM proposal_instances pi JOIN proposals p USING (proposal_id)
        WHERE pi.source_id IN ('mapfre_am','sec_npx')
          AND p.meeting_id IN (SELECT meeting_id FROM meetings m
               WHERE EXISTS (SELECT 1 FROM proposals q JOIN votes v2
                   USING (proposal_id)
                   WHERE q.meeting_id=m.meeting_id
                   AND v2.source_id='mapfre_am')
               AND EXISTS (SELECT 1 FROM proposals q JOIN votes v2
                   USING (proposal_id)
                   WHERE q.meeting_id=m.meeting_id
                   AND v2.source_id='sec_npx'))""").fetchall()

    by_meeting: dict[str, dict[str, list]] = {}
    for pid, sid, text, num, mid in insts:
        by_meeting.setdefault(mid, {}).setdefault(sid, []).append(
            {"pid": pid, "text": text, "num": num})

    import re
    def norm(t):
        return re.sub(r"[^a-z0-9 ]", "", (t or "").lower()).strip()

    rows = []
    for mid, issuer, mdate in shared:
        sides = by_meeting.get(mid, {})
        mp = sides.get("mapfre_am", [])
        nx = sides.get("sec_npx", [])
        npx_nums = {i["num"] for i in nx if i["num"]}
        npx_texts = {norm(i["text"]) for i in nx}
        m_nums = [i["num"] for i in mp if i["num"]]
        n_exact_num = sum(1 for i in mp
                          if i["num"] and i["num"] in npx_nums)
        n_exact_txt = sum(1 for i in mp if norm(i["text"]) in npx_texts)
        rows.append({
            "meeting_id": mid, "issuer": issuer,
            "meeting_date": str(mdate),
            "mapfre_instances": len(mp), "npx_instances": len(nx),
            "mapfre_item_numbers": len(m_nums),
            "npx_item_numbers": len(npx_nums),
            "exact_number_matches": n_exact_num,
            "exact_text_matches": n_exact_txt,
            "unresolved_mapfre": max(0, len(mp) - n_exact_num - n_exact_txt),
        })

    t = pa.Table.from_pylist(rows) if rows else pa.table({})
    pq.write_table(t, OUT_PQ)

    n_num = sum(r["exact_number_matches"] for r in rows)
    n_txt = sum(r["exact_text_matches"] for r in rows)
    n_m = sum(r["mapfre_instances"] for r in rows)
    n_x = sum(r["npx_instances"] for r in rows)
    md = f"""# G9 preview — MAPFRE × SEC N-PX same-meeting reconciliation corpus

Generated by `scripts/g9_preview.py` over the local gold build.
Counting only; no proposal matching applied.

## Totals

- shared meetings (both sources observed): **{len(rows)}**
- MAPFRE proposal instances: **{n_m}**
- N-PX proposal instances: **{n_x}**
- MAPFRE rows pairable by exact item number: **{n_num}**
- MAPFRE rows pairable by exact normalized text: **{n_txt}**
- unresolved MAPFRE instances: **{n_m - n_num - n_txt}**

N-PX filers rarely carry item numbers (the SEC form does not require the
ballot number), so exact-number pairing is expected to be rare; the real
G9 work is text+category matching between MAPFRE's ISS-style proposal
titles and N-PX `voteDescription` free text.

## Per-meeting

| issuer | date | mapfre | npx | #num | #text |
|---|---|---|---|---|---|
"""
    md += "\n".join(
        f"| {r['issuer']} | {r['meeting_date']} | {r['mapfre_instances']} "
        f"| {r['npx_instances']} | {r['exact_number_matches']} "
        f"| {r['exact_text_matches']} |" for r in rows[:60])
    if len(rows) > 60:
        md += f"\n| … | | | | | |\n\n({len(rows)-60} more meetings in the parquet corpus)"
    OUT_MD.write_text(md, encoding="utf-8")
    print(f"shared meetings={len(rows)} mapfre_instances={n_m} "
          f"npx_instances={n_x} num={n_num} text={n_txt}")
    print(f"wrote {OUT_PQ} and {OUT_MD}")


if __name__ == "__main__":
    main()
